/* parser generated by jison 0.4.18 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var parser = (function(){
var o=function(k,v,o,l){for(o=o||{},l=k.length;l--;o[k[l]]=v);return o},$V0=[1,23],$V1=[1,22],$V2=[2,35],$V3=[1,29],$V4=[10,11],$V5=[2,15,17],$V6=[1,40],$V7=[1,39],$V8=[2,42,43,44],$V9=[2,40,43],$Va=[1,61],$Vb=[1,59],$Vc=[1,54],$Vd=[1,55],$Ve=[1,56],$Vf=[1,57],$Vg=[1,58],$Vh=[1,60],$Vi=[21,22],$Vj=[2,43],$Vk=[1,68],$Vl=[1,69],$Vm=[1,71],$Vn=[21,22,34],$Vo=[2,18,21,22,28,29,30,31,32,33,34],$Vp=[2,11,18,21,22,26,27,28,29,30,31,32,33,34],$Vq=[18,21,22,43];
var parser = {trace: function trace () { },
yy: {},
symbols_: {"error":2,"inicio":3,"WISON":4,"APERTURA":5,"bloque_lex":6,"bloque_syntax":7,"cierre_wison":8,"EOF":9,"CIERRE_WISON":10,"OPCIONAL":11,"LEX":12,"BLOQUE_ABRE":13,"lista_terminales":14,"BLOQUE_CIERRA":15,"declaracion_terminal":16,"TERMINAL":17,"ID_TERMINAL":18,"ASIGNACION":19,"expresion_regular":20,"PUNTO_COMA":21,"OR":22,"expresion_concatenada":23,"expresion_unaria":24,"expresion_primaria":25,"KLEENE":26,"MAS":27,"CADENA":28,"RANGO_NUMERO":29,"RANGO_LETRA_MINUSCULA":30,"RANGO_LETRA_MAYUSCULA":31,"RANGO_ABECEDARIO":32,"PARENTESIS_ABRE":33,"PARENTESIS_CIERRA":34,"SYNTAX_PARSER":35,"SYNTAX_BLOQUE_ABRE":36,"lista_no_terminales":37,"simbolo_inicial":38,"lista_producciones":39,"SYNTAX_BLOQUE_CIERRA":40,"declaracion_no_terminal":41,"NO_TERMINAL":42,"ID_NO_TERMINAL":43,"SIMBOLO_INICIAL":44,"produccion":45,"FLECHA":46,"cuerpo_produccion":47,"alternativa":48,"lista_simbolos":49,"simbolo":50,"$accept":0,"$end":1},
terminals_: {2:"error",4:"WISON",5:"APERTURA",9:"EOF",10:"CIERRE_WISON",11:"OPCIONAL",12:"LEX",13:"BLOQUE_ABRE",15:"BLOQUE_CIERRA",17:"TERMINAL",18:"ID_TERMINAL",19:"ASIGNACION",21:"PUNTO_COMA",22:"OR",26:"KLEENE",27:"MAS",28:"CADENA",29:"RANGO_NUMERO",30:"RANGO_LETRA_MINUSCULA",31:"RANGO_LETRA_MAYUSCULA",32:"RANGO_ABECEDARIO",33:"PARENTESIS_ABRE",34:"PARENTESIS_CIERRA",35:"SYNTAX_PARSER",36:"SYNTAX_BLOQUE_ABRE",40:"SYNTAX_BLOQUE_CIERRA",42:"NO_TERMINAL",43:"ID_NO_TERMINAL",44:"SIMBOLO_INICIAL",46:"FLECHA"},
productions_: [0,[3,6],[3,2],[8,1],[8,2],[6,4],[6,3],[6,2],[14,2],[14,1],[16,5],[16,2],[20,3],[20,1],[23,2],[23,1],[24,2],[24,2],[24,2],[24,1],[25,1],[25,1],[25,1],[25,1],[25,1],[25,1],[25,3],[25,1],[7,6],[7,5],[7,3],[7,2],[37,2],[37,1],[41,3],[38,3],[39,2],[39,1],[45,4],[45,2],[47,3],[47,1],[48,1],[48,0],[49,2],[49,1],[50,1],[50,1]],
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
case 1:

        this.$ = {
            tipo: 'Wison',
            lex: $$[$0-3],
            syntax: $$[$0-2],
            linea: _$[$0-5].first_line,
            columna: _$[$0-5].first_column
        };
        return {
            ast: this.$,
            tokens: yy.manejador.getToken(),
            errores: yy.manejador.getError()
        };
    
break;
case 2:

        yy.manejador.errorEstructuraWison(
            '',
            _$[$0-1].first_line,
            _$[$0-1].first_column,
            "Falta cerrar el archivo con ?Wison"
        );

        return {
            ast: null,
            tokens: yy.manejador.getToken(),
            errores: yy.manejador.getError()
        };
    
break;
case 3:

        this.$ = '?Wison';
    
break;
case 4:

        this.$ = '? Wison';
    
break;
case 5:

        this.$ = {
            tipo: 'BloqueLexico',
            terminales: $$[$0-1],
            linea: _$[$0-3].first_line,
            columna: _$[$0-3].first_column
        };
    
break;
case 6:

        this.$ = {
            tipo: 'BloqueLexico',
            terminales: [],
            linea: _$[$0-2].first_line,
            columna: _$[$0-2].first_column
        };
    
break;
case 7:

        yy.manejador.errorBloqueLex(
            yytext,
            _$[$0-1].first_line,
            _$[$0-1].first_column + 1
        );
        this.$ = { tipo: 'BloqueLexico', terminales: [], linea: _$[$0-1].first_line, columna: _$[$0-1].first_column };
    
break;
case 8: case 32: case 36:

        this.$ = $$[$0-1];
        this.$.push($$[$0]);
    
break;
case 9: case 33: case 37:

        this.$ = [$$[$0]];
    
break;
case 10:

        this.$ = {
            tipo: 'DeclaracionTerminal',
            nombre: $$[$0-3],
            expresion: $$[$0-1],
            linea: _$[$0-4].first_line,
            columna: _$[$0-4].first_column
        };
        yy.manejador.agregarToken(
            $$[$0-3],
            _$[$0-3].first_line,
            _$[$0-3].first_column + 1,
            "Expresión regular: " + yy.manejador.regexToString($$[$0-1]),
            "TERMINAL"
        );

    
break;
case 11:

        yy.manejador.errorDeclaracionTerminal(
            yytext,
            _$[$0-1].first_line,
            _$[$0-1].first_column + 1
        );
        this.$ = null;
    
break;
case 12:

        this.$ = { tipo: 'Union', izq: $$[$0-2], der: $$[$0], linea: _$[$0-2].first_line, columna: _$[$0-2].first_column };
    
break;
case 13: case 15: case 19: case 41: case 42:

        this.$ = $$[$0];
    
break;
case 14:

        this.$ = { tipo: 'Concatenacion', izq: $$[$0-1], der: $$[$0], linea: _$[$0-1].first_line, columna: _$[$0-1].first_column };
    
break;
case 16:

        this.$ = { tipo: 'Kleene', expr: $$[$0-1], linea: _$[$0-1].first_line, columna: _$[$0-1].first_column };
    
break;
case 17:

        this.$ = { tipo: 'CerraduraPositiva', expr: $$[$0-1], linea: _$[$0-1].first_line, columna: _$[$0-1].first_column };
    
break;
case 18:

        this.$ = { tipo: 'Opcional', expr: $$[$0-1], linea: _$[$0-1].first_line, columna: _$[$0-1].first_column };
    
break;
case 20:

        this.$ = { tipo: 'Caracter', valor: $$[$0].slice(1,-1), linea: _$[$0].first_line, columna: _$[$0].first_column };
    
break;
case 21:

        this.$ = { tipo: 'Rango', valor: '[0-9]', linea: _$[$0].first_line, columna: _$[$0].first_column };
    
break;
case 22:

        this.$ = { tipo: 'Rango', valor: '[a-z]', linea: _$[$0].first_line, columna: _$[$0].first_column };
    
break;
case 23:

        this.$ = { tipo: 'Rango', valor: '[A-Z]', linea: _$[$0].first_line, columna: _$[$0].first_column };
    
break;
case 24:

        this.$ = { tipo: 'Rango', valor: '[aA-zZ]', linea: _$[$0].first_line, columna: _$[$0].first_column };
    
break;
case 25:

        this.$ = { tipo: 'ReferenciaTerminal', nombre: $$[$0], linea: _$[$0].first_line, columna: _$[$0].first_column };
    
break;
case 26:

        this.$ = { tipo: 'Grupo', expr: $$[$0-1], linea: _$[$0-2].first_line, columna: _$[$0-2].first_column };
    
break;
case 27:

       yy.manejador.errorExpresionRegular(
            yytext,
            _$[$0].first_line,
            _$[$0].first_column + 1
        );

        this.$ = { tipo: 'Error', linea: _$[$0].first_line, columna: _$[$0].first_column };
    
break;
case 28:

        this.$ = {
            tipo: 'BloqueSintactico',
            noTerminales: $$[$0-3],
            simboloInicial: $$[$0-2],
            producciones: $$[$0-1],
            linea: _$[$0-5].first_line,
            columna: _$[$0-5].first_column
        };
    
break;
case 29:

        yy.manejador.errorSintactico(        
            '',
            _$[$0-4].first_line,
            _$[$0-4].first_column + 1,
            'Falta declarar el simbolo inicial: Initial_Sim %_Nombre ;'
        );
        this.$ = {
            tipo: 'BloqueSintactico',
            noTerminales: $$[$0-2],
            simboloInicial: null,
            producciones: $$[$0-1],
            linea: _$[$0-4].first_line,
            columna: _$[$0-4].first_column
        };
    
break;
case 30:

        this.$ = {
            tipo: 'BloqueSintactico',
            noTerminales: [],
            simboloInicial: null,
            producciones: [],
            linea: _$[$0-2].first_line,
            columna: _$[$0-2].first_column
        };
    
break;
case 31:

        yy.manejador.errorBloqueSyntax(
            yytext,
            _$[$0-1].first_line,
            _$[$0-1].first_column + 1
        );

        this.$ = {
            tipo: 'BloqueSintactico',
            noTerminales: [],
            simboloInicial: null,
            producciones: [],
            linea: _$[$0-1].first_line,
            columna: _$[$0-1].first_column
        };
    
break;
case 34:

        this.$ = {
            tipo: 'DeclaracionNoTerminal',
            nombre: $$[$0-1],
            linea: _$[$0-2].first_line,
            columna: _$[$0-2].first_column
        };
        yy.manejador.agregarToken(
            $$[$0-1],
            _$[$0-1].first_line,
            _$[$0-1].first_column + 1,
            "No Terminal declarado",
            "NO_TERMINAL"
        );
        
    
break;
case 35:

        this.$ = {
            tipo: 'SimboloInicial',
            nombre: $$[$0-1],
            linea: _$[$0-2].first_line,
            columna: _$[$0-2].first_column
        };
        yy.manejador.agregarToken(
            $$[$0-1],
            _$[$0-1].first_line,
            _$[$0-1].first_column + 1,
            "Simbolo de inicio",
            "SIMBOLO_INICIAL"
        );
    
break;
case 38:


        let textoProduccion =
            $$[$0-3] + " → " +
            yy.manejador.produccionToString($$[$0-1]);

        this.$ = {
            tipo: 'Produccion',
            cabeza: $$[$0-3],
            cuerpo: $$[$0-1]
        };

        yy.manejador.agregarToken(
            textoProduccion,
            _$[$0-3].first_line,
            _$[$0-3].first_column + 1,
            "Producción gramatical",
            "PRODUCCION"
        );

    
break;
case 39:

        yy.manejador.errorProduccion(
            yytext,
            _$[$0-1].first_line,
            _$[$0-1].first_column + 1
        );

        this.$ = null;
    
break;
case 40:

        this.$ = {
            tipo:'Alternativa',
            opciones:[
                ...($$[$0-2].tipo==='Alternativa' ? $$[$0-2].opciones : [$$[$0-2]]),
                $$[$0]
            ]
        };
    
break;
case 43:

        this.$ = {
            tipo:'Secuencia',
            simbolos:[],
            epsilon:true
        };
    
break;
case 44:

        this.$ = { tipo: 'Secuencia', simbolos: [...($$[$0-1].tipo === 'Secuencia' ? $$[$0-1].simbolos : [$$[$0-1]]), $$[$0]] };
    
break;
case 45:

        this.$ = { tipo: 'Secuencia', simbolos: [$$[$0]] };
    
break;
case 46:

        this.$ = { tipo: 'SimboloTerminal', nombre: $$[$0], linea: _$[$0].first_line, columna: _$[$0].first_column };
    
break;
case 47:

        this.$ = { tipo: 'SimboloNoTerminal', nombre: $$[$0], linea: _$[$0].first_line, columna: _$[$0].first_column };
    
break;
}
},
table: [{2:[1,3],3:1,4:[1,2]},{1:[3]},{5:[1,4]},{9:[1,5]},{2:[1,8],6:6,12:[1,7]},{1:[2,2]},{2:[1,11],7:9,35:[1,10]},{13:[1,12]},{15:[1,13]},{8:14,10:[1,15],11:[1,16]},{36:[1,17]},{40:[1,18]},{2:$V0,14:19,15:[1,20],16:21,17:$V1},o($V2,[2,7]),{9:[1,24]},{9:[2,3]},{4:[1,25]},{37:26,40:[1,27],41:28,42:$V3},o($V4,[2,31]),{2:$V0,15:[1,30],16:31,17:$V1},o($V2,[2,6]),o($V5,[2,9]),{18:[1,32]},{21:[1,33]},{1:[2,1]},{9:[2,4]},{2:$V6,38:34,39:35,41:36,42:$V3,43:$V7,44:[1,37],45:38},o($V4,[2,30]),o($V8,[2,33]),{43:[1,41]},o($V2,[2,5]),o($V5,[2,8]),{19:[1,42]},o($V5,[2,11]),{2:$V6,39:43,43:$V7,45:38},{2:$V6,40:[1,44],43:$V7,45:45},o($V8,[2,32]),{43:[1,46]},o($V9,[2,37]),{46:[1,47]},{21:[1,48]},{21:[1,49]},{2:$Va,18:$Vb,20:50,23:51,24:52,25:53,28:$Vc,29:$Vd,30:$Ve,31:$Vf,32:$Vg,33:$Vh},{2:$V6,40:[1,62],43:$V7,45:45},o($V4,[2,29]),o($V9,[2,36]),{21:[1,63]},o($Vi,$Vj,{47:64,48:65,49:66,50:67,18:$Vk,43:$Vl}),o($V9,[2,39]),o($V8,[2,34]),{21:[1,70],22:$Vm},o($Vn,[2,13],{25:53,24:72,2:$Va,18:$Vb,28:$Vc,29:$Vd,30:$Ve,31:$Vf,32:$Vg,33:$Vh}),o($Vo,[2,15]),o($Vo,[2,19],{11:[1,75],26:[1,73],27:[1,74]}),o($Vp,[2,20]),o($Vp,[2,21]),o($Vp,[2,22]),o($Vp,[2,23]),o($Vp,[2,24]),o($Vp,[2,25]),{2:$Va,18:$Vb,20:76,23:51,24:52,25:53,28:$Vc,29:$Vd,30:$Ve,31:$Vf,32:$Vg,33:$Vh},o($Vp,[2,27]),o($V4,[2,28]),o($Vj,$V2),{21:[1,77],22:[1,78]},o($Vi,[2,41]),o($Vi,[2,42],{50:79,18:$Vk,43:$Vl}),o($Vq,[2,45]),o($Vq,[2,46]),o($Vq,[2,47]),o($V5,[2,10]),{2:$Va,18:$Vb,23:80,24:52,25:53,28:$Vc,29:$Vd,30:$Ve,31:$Vf,32:$Vg,33:$Vh},o($Vo,[2,14]),o($Vo,[2,16]),o($Vo,[2,17]),o($Vo,[2,18]),{22:$Vm,34:[1,81]},o($V9,[2,38]),o($Vi,$Vj,{49:66,50:67,48:82,18:$Vk,43:$Vl}),o($Vq,[2,44]),o($Vn,[2,12],{25:53,24:72,2:$Va,18:$Vb,28:$Vc,29:$Vd,30:$Ve,31:$Vf,32:$Vg,33:$Vh}),o($Vp,[2,26]),o($Vi,[2,40])],
defaultActions: {5:[2,2],15:[2,3],24:[2,1],25:[2,4]},
parseError: function parseError (str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        var error = new Error(str);
        error.hash = hash;
        throw error;
    }
},
parse: function parse (input) {
    var self = this,
        stack = [0],
        tstack = [], // token stack
        vstack = [null], // semantic value stack
        lstack = [], // location stack
        table = this.table,
        yytext = '',
        yylineno = 0,
        yyleng = 0,
        recovering = 0,
        TERROR = 2,
        EOF = 1;

    var args = lstack.slice.call(arguments, 1);

    //this.reductionCount = this.shiftCount = 0;

    var lexer = Object.create(this.lexer);
    var sharedState = { yy: {} };
    // copy state
    for (var k in this.yy) {
      if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
        sharedState.yy[k] = this.yy[k];
      }
    }

    lexer.setInput(input, sharedState.yy);
    sharedState.yy.lexer = lexer;
    sharedState.yy.parser = this;
    if (typeof lexer.yylloc == 'undefined') {
        lexer.yylloc = {};
    }
    var yyloc = lexer.yylloc;
    lstack.push(yyloc);

    var ranges = lexer.options && lexer.options.ranges;

    if (typeof sharedState.yy.parseError === 'function') {
        this.parseError = sharedState.yy.parseError;
    } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
    }

    function popStack (n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }

_token_stack:
    var lex = function () {
        var token;
        token = lexer.lex() || EOF;
        // if token isn't its numeric value, convert
        if (typeof token !== 'number') {
            token = self.symbols_[token] || token;
        }
        return token;
    }

    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        // retreive state number from top of stack
        state = stack[stack.length - 1];

        // use default actions if available
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == 'undefined') {
                symbol = lex();
            }
            // read action for current state and first input
            action = table[state] && table[state][symbol];
        }

_handle_error:
        // handle parse error
        if (typeof action === 'undefined' || !action.length || !action[0]) {
            var error_rule_depth;
            var errStr = '';

            // Return the rule stack depth where the nearest error rule can be found.
            // Return FALSE when no error recovery rule was found.
            function locateNearestErrorRecoveryRule(state) {
                var stack_probe = stack.length - 1;
                var depth = 0;

                // try to recover from error
                for(;;) {
                    // check for error recovery rule in this state
                    if ((TERROR.toString()) in table[state]) {
                        return depth;
                    }
                    if (state === 0 || stack_probe < 2) {
                        return false; // No suitable error recovery rule available.
                    }
                    stack_probe -= 2; // popStack(1): [symbol, action]
                    state = stack[stack_probe];
                    ++depth;
                }
            }

            if (!recovering) {
                // first see if there's any chance at hitting an error recovery rule:
                error_rule_depth = locateNearestErrorRecoveryRule(state);

                // Report error
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p > TERROR) {
                        expected.push("'"+this.terminals_[p]+"'");
                    }
                }
                if (lexer.showPosition) {
                    errStr = 'Parse error on line '+(yylineno+1)+":\n"+lexer.showPosition()+"\nExpecting "+expected.join(', ') + ", got '" + (this.terminals_[symbol] || symbol)+ "'";
                } else {
                    errStr = 'Parse error on line '+(yylineno+1)+": Unexpected " +
                                  (symbol == EOF ? "end of input" :
                                              ("'"+(this.terminals_[symbol] || symbol)+"'"));
                }
                this.parseError(errStr, {
                    text: lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: lexer.yylineno,
                    loc: yyloc,
                    expected: expected,
                    recoverable: (error_rule_depth !== false)
                });
            } else if (preErrorSymbol !== EOF) {
                error_rule_depth = locateNearestErrorRecoveryRule(state);
            }

            // just recovered from another error
            if (recovering == 3) {
                if (symbol === EOF || preErrorSymbol === EOF) {
                    throw new Error(errStr || 'Parsing halted while starting to recover from another error.');
                }

                // discard current lookahead and grab another
                yyleng = lexer.yyleng;
                yytext = lexer.yytext;
                yylineno = lexer.yylineno;
                yyloc = lexer.yylloc;
                symbol = lex();
            }

            // try to recover from error
            if (error_rule_depth === false) {
                throw new Error(errStr || 'Parsing halted. No suitable error recovery rule available.');
            }
            popStack(error_rule_depth);

            preErrorSymbol = (symbol == TERROR ? null : symbol); // save the lookahead token
            symbol = TERROR;         // insert generic error symbol as new lookahead
            state = stack[stack.length-1];
            action = table[state] && table[state][TERROR];
            recovering = 3; // allow 3 real symbols to be shifted before reporting a new error
        }

        // this shouldn't happen, unless resolve defaults are off
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error('Parse Error: multiple actions possible at state: '+state+', token: '+symbol);
        }

        switch (action[0]) {
            case 1: // shift
                //this.shiftCount++;

                stack.push(symbol);
                vstack.push(lexer.yytext);
                lstack.push(lexer.yylloc);
                stack.push(action[1]); // push state
                symbol = null;
                if (!preErrorSymbol) { // normal execution/no error
                    yyleng = lexer.yyleng;
                    yytext = lexer.yytext;
                    yylineno = lexer.yylineno;
                    yyloc = lexer.yylloc;
                    if (recovering > 0) {
                        recovering--;
                    }
                } else {
                    // error just occurred, resume old lookahead f/ before error
                    symbol = preErrorSymbol;
                    preErrorSymbol = null;
                }
                break;

            case 2:
                // reduce
                //this.reductionCount++;

                len = this.productions_[action[1]][1];

                // perform semantic action
                yyval.$ = vstack[vstack.length-len]; // default to $$ = $1
                // default location, uses first token for firsts, last for lasts
                yyval._$ = {
                    first_line: lstack[lstack.length-(len||1)].first_line,
                    last_line: lstack[lstack.length-1].last_line,
                    first_column: lstack[lstack.length-(len||1)].first_column,
                    last_column: lstack[lstack.length-1].last_column
                };
                if (ranges) {
                  yyval._$.range = [lstack[lstack.length-(len||1)].range[0], lstack[lstack.length-1].range[1]];
                }
                r = this.performAction.apply(yyval, [yytext, yyleng, yylineno, sharedState.yy, action[1], vstack, lstack].concat(args));

                if (typeof r !== 'undefined') {
                    return r;
                }

                // pop off stack
                if (len) {
                    stack = stack.slice(0,-1*len*2);
                    vstack = vstack.slice(0, -1*len);
                    lstack = lstack.slice(0, -1*len);
                }

                stack.push(this.productions_[action[1]][0]);    // push nonterminal (reduce)
                vstack.push(yyval.$);
                lstack.push(yyval._$);
                // goto new state = table[STATE][NONTERMINAL]
                newState = table[stack[stack.length-2]][stack[stack.length-1]];
                stack.push(newState);
                break;

            case 3:
                // accept
                return true;
        }

    }

    return true;
}};
/* generated by jison-lex 0.3.4 */
var lexer = (function(){
var lexer = ({

EOF:1,

parseError:function parseError(str, hash) {
        if (this.yy.parser) {
            this.yy.parser.parseError(str, hash);
        } else {
            throw new Error(str);
        }
    },

// resets the lexer, sets new input
setInput:function (input, yy) {
        this.yy = yy || this.yy || {};
        this._input = input;
        this._more = this._backtrack = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {
            first_line: 1,
            first_column: 0,
            last_line: 1,
            last_column: 0
        };
        if (this.options.ranges) {
            this.yylloc.range = [0,0];
        }
        this.offset = 0;
        return this;
    },

// consumes and returns one char from the input
input:function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno++;
            this.yylloc.last_line++;
        } else {
            this.yylloc.last_column++;
        }
        if (this.options.ranges) {
            this.yylloc.range[1]++;
        }

        this._input = this._input.slice(1);
        return ch;
    },

// unshifts one char (or a string) into the input
unput:function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - 1);
        this.matched = this.matched.substr(0, this.matched.length - 1);

        if (lines.length - 1) {
            this.yylineno -= lines.length - 1;
        }
        var r = this.yylloc.range;

        this.yylloc = {
            first_line: this.yylloc.first_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.first_column,
            last_column: lines ?
                (lines.length === oldLines.length ? this.yylloc.first_column : 0)
                 + oldLines[oldLines.length - lines.length].length - lines[0].length :
              this.yylloc.first_column - len
        };

        if (this.options.ranges) {
            this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
    },

// When called from action, caches matched text and appends it on next action
more:function () {
        this._more = true;
        return this;
    },

// When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
reject:function () {
        if (this.options.backtrack_lexer) {
            this._backtrack = true;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });

        }
        return this;
    },

// retain first n characters of the match
less:function (n) {
        this.unput(this.match.slice(n));
    },

// displays already matched input, i.e. for error messages
pastInput:function () {
        var past = this.matched.substr(0, this.matched.length - this.match.length);
        return (past.length > 20 ? '...':'') + past.substr(-20).replace(/\n/g, "");
    },

// displays upcoming input, i.e. for error messages
upcomingInput:function () {
        var next = this.match;
        if (next.length < 20) {
            next += this._input.substr(0, 20-next.length);
        }
        return (next.substr(0,20) + (next.length > 20 ? '...' : '')).replace(/\n/g, "");
    },

// displays the character position where the lexing error occurred, i.e. for error messages
showPosition:function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join("-");
        return pre + this.upcomingInput() + "\n" + c + "^";
    },

// test the lexed token: return FALSE when not a match, otherwise return token
test_match:function(match, indexed_rule) {
        var token,
            lines,
            backup;

        if (this.options.backtrack_lexer) {
            // save context
            backup = {
                yylineno: this.yylineno,
                yylloc: {
                    first_line: this.yylloc.first_line,
                    last_line: this.last_line,
                    first_column: this.yylloc.first_column,
                    last_column: this.yylloc.last_column
                },
                yytext: this.yytext,
                match: this.match,
                matches: this.matches,
                matched: this.matched,
                yyleng: this.yyleng,
                offset: this.offset,
                _more: this._more,
                _input: this._input,
                yy: this.yy,
                conditionStack: this.conditionStack.slice(0),
                done: this.done
            };
            if (this.options.ranges) {
                backup.yylloc.range = this.yylloc.range.slice(0);
            }
        }

        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno += lines.length;
        }
        this.yylloc = {
            first_line: this.yylloc.last_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.last_column,
            last_column: lines ?
                         lines[lines.length - 1].length - lines[lines.length - 1].match(/\r?\n?/)[0].length :
                         this.yylloc.last_column + match[0].length
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
            this.yylloc.range = [this.offset, this.offset += this.yyleng];
        }
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(this, this.yy, this, indexed_rule, this.conditionStack[this.conditionStack.length - 1]);
        if (this.done && this._input) {
            this.done = false;
        }
        if (token) {
            return token;
        } else if (this._backtrack) {
            // recover context
            for (var k in backup) {
                this[k] = backup[k];
            }
            return false; // rule action called reject() implying the next rule should be tested instead.
        }
        return false;
    },

// return next match in input
next:function () {
        if (this.done) {
            return this.EOF;
        }
        if (!this._input) {
            this.done = true;
        }

        var token,
            match,
            tempMatch,
            index;
        if (!this._more) {
            this.yytext = '';
            this.match = '';
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
            tempMatch = this._input.match(this.rules[rules[i]]);
            if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                match = tempMatch;
                index = i;
                if (this.options.backtrack_lexer) {
                    token = this.test_match(tempMatch, rules[i]);
                    if (token !== false) {
                        return token;
                    } else if (this._backtrack) {
                        match = false;
                        continue; // rule action called reject() implying a rule MISmatch.
                    } else {
                        // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                        return false;
                    }
                } else if (!this.options.flex) {
                    break;
                }
            }
        }
        if (match) {
            token = this.test_match(match, rules[index]);
            if (token !== false) {
                return token;
            }
            // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
            return false;
        }
        if (this._input === "") {
            return this.EOF;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. Unrecognized text.\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });
        }
    },

// return next match that has a token
lex:function lex () {
        var r = this.next();
        if (r) {
            return r;
        } else {
            return this.lex();
        }
    },

// activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
begin:function begin (condition) {
        this.conditionStack.push(condition);
    },

// pop the previously active lexer condition state off the condition stack
popState:function popState () {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
            return this.conditionStack.pop();
        } else {
            return this.conditionStack[0];
        }
    },

// produce the lexer rule set which is active for the currently active lexer condition state
_currentRules:function _currentRules () {
        if (this.conditionStack.length && this.conditionStack[this.conditionStack.length - 1]) {
            return this.conditions[this.conditionStack[this.conditionStack.length - 1]].rules;
        } else {
            return this.conditions["INITIAL"].rules;
        }
    },

// return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
topState:function topState (n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
            return this.conditionStack[n];
        } else {
            return "INITIAL";
        }
    },

// alias for begin(condition)
pushState:function pushState (condition) {
        this.begin(condition);
    },

// return the number of states currently on the stack
stateStackSize:function stateStackSize() {
        return this.conditionStack.length;
    },
options: {"case-insensitive":true},
performAction: function anonymous(yy,yy_,$avoiding_name_collisions,YY_START) {
var YYSTATE=YY_START;
switch($avoiding_name_collisions) {
case 0:/* ignorar espacios */
break;
case 1:/* comentario línea */
break;
case 2:/* comentario multilinea */
break;
case 3:return 29;
break;
case 4:return 30;
break;
case 5:return 31;
break;
case 6:return 32;
break;
case 7:return 4;
break;
case 8:return 12;
break;
case 9:return 17;
break;
case 10:return 42;
break;
case 11:return 35;
break;
case 12:return 44;
break;
case 13:return 46;
break;
case 14:return 19;
break;
case 15:return 36;
break;
case 16:return 40;
break;
case 17:return 13;
break;
case 18:return 15;
break;
case 19:return 33;
break;
case 20:return 34;
break;
case 21:return 'CORCHETE_ABRE';
break;
case 22:return 'CORCHETE_CIERRA';
break;
case 23:return 21;
break;
case 24:return 22;
break;
case 25:return 27;
break;
case 26:return 26;
break;
case 27:return 'PUNTO';    
break;
case 28:return 'GUION';
break;
case 29:return 'NOT';
break;
case 30:return 'NEGACION';
break;
case 31:return 5;
break;
case 32:return 10;
break;
case 33:return 11;
break;
case 34:return 28;
break;
case 35:return 18;
break;
case 36:return 43;
break;
case 37:return 9;
break;
case 38:
    yy.manejador.errorLexico(
        yy_.yytext,
        yy_.yylloc.first_line,
        yy_.yylloc.first_column + 1
    );

break;
}
},
rules: [/^(?:\s+)/i,/^(?:#.*)/i,/^(?:[/][*][*]([^*]|[*]+[^*/])*[*]+[/])/i,/^(?:\[0-9\])/i,/^(?:\[a-z\])/i,/^(?:\[A-Z\])/i,/^(?:\[aA-zZ\])/i,/^(?:Wison\b)/i,/^(?:Lex\b)/i,/^(?:Terminal\b)/i,/^(?:No_Terminal\b)/i,/^(?:Syntax\b)/i,/^(?:Initial_Sim\b)/i,/^(?:<=)/i,/^(?:<-)/i,/^(?:\{\{:)/i,/^(?::\}\})/i,/^(?:\{:)/i,/^(?::\})/i,/^(?:\()/i,/^(?:\))/i,/^(?:\[)/i,/^(?:\])/i,/^(?:;)/i,/^(?:\|)/i,/^(?:\+)/i,/^(?:\*)/i,/^(?:\.)/i,/^(?:-)/i,/^(?:!)/i,/^(?:~)/i,/^(?:¿)/i,/^(?:\?Wison\b)/i,/^(?:\?)/i,/^(?:[']([^'])*['])/i,/^(?:\$_[a-zA-Z0-9_]+)/i,/^(?:%_[a-zA-Z0-9_]+)/i,/^(?:$)/i,/^(?:.)/i],
conditions: {"INITIAL":{"rules":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38],"inclusive":true}}
});
return lexer;
})();
parser.lexer = lexer;
function Parser () {
  this.yy = {};
}
Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();


if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
exports.parser = parser;
exports.Parser = parser.Parser;
exports.parse = function () { return parser.parse.apply(parser, arguments); };
exports.main = function commonjsMain (args) {
    if (!args[1]) {
        console.log('Usage: '+args[0]+' FILE');
        process.exit(1);
    }
    var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
    return exports.parser.parse(source);
};
if (typeof module !== 'undefined' && require.main === module) {
  exports.main(process.argv.slice(1));
}
}
if (typeof window !== 'undefined') {
  window.wisonParser = parser;
}